Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 12288  
    vb.cpus = 6
  end

  config.vm.define "gitlab-vm" do |vm1|
    vm1.vm.hostname = "gitlab-vm"
    vm1.vm.network "private_network", ip: "192.168.56.10"

    vm1.vm.provision "shell", inline: <<-SHELL
      sudo apt update -y
      sudo apt install -y docker.io

      sudo docker run -d \
        --hostname 192.168.100.75 \
        -p 80:80 \
        -p 443:443 \
        -p 8022:22 \
        --name gitlab \
        -e GITLAB_OMNIBUS_CONFIG="external_url='http://192.168.56.10'; gitlab_rails['gitlab_shell_ssh_port']=8022" \
        -v gitlab-data:/var/opt/gitlab \
        -v ~/gitlab-config:/etc/gitlab \
        gitlab/gitlab-ce:latest
      SHELL
  end
  
end