Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096 
    vb.cpus = 2
  end

  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1"
    vm1.vm.network "private_network", ip: "192.168.56.10"

    vm1.vm.synced_folder "./vm1_data", "/home/vagrant/vm1_data", type: "virtualbox"

    vm1.vm.provision "shell", inline: <<-SHELL
      sudo apt update -y
      sudo apt install -y docker.io docker-compose
      sudo systemctl enable --now docker

      cd /home/vagrant/vm1_data
      sudo docker-compose up -d
    SHELL
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: "192.168.56.11"

    vm2.vm.provision "shell", inline: <<-SHELL
      sudo apt update -y
      sudo apt install -y docker.io

      sudo docker run -d --name zabbix-agent \
        -e ZBX_SERVER_HOST=192.168.56.10 \
        -e HOSTNAME=vm2 \
        -p 10050:10050 \
        zabbix/zabbix-agent:alpine-7.0-latest
    SHELL
  end

end